#!/bin/bash

service::config_set() {
  config::check_or_set $1 $2 $SERVICE_CONFIG "${@:3}"
}

check() {
  if [ "$DEBUG" = "true" ]; then
    log::info "[DEBUG][service]: $SERVICE_CONFIG"
    cat $SERVICE_CONFIG
  fi

  if [ ! -f "${SERVICE_CONFIGS}/config.yml" ]; then
    cp ${SERVICE_DIR}/conf/config.yml ${SERVICE_CONFIGS}/config.yml
  fi

  # service::config_set SERVICE_PROMETHEUS_PORT text "Port" 9000
}

check $@
